# # MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
# #   - '10.14'                # [osx and x86_64]
# MACOSX_SDK_VERSION:        # [osx]
#   - '11.3'                 # [osx]
# CONDA_BUILD_SYSROOT:       # [osx]
#   - /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk  # [osx]
# c_compiler:  # [win]
#   - vs2019   # [win]
# cxx_compiler:  # [win]
#   - vs2019   # [win]
# macos_machine:
#   - x86_64-apple-darwin20.0.0  # [osx and x86_64]
#   - arm64-apple-darwin20.0.0   # [osx and arm64]
